import { BrainCircuit, AlertCircle, ArrowRight } from "lucide-react";

export default function RecommendationsPage() {
  return (
    <div className="max-w-7xl mx-auto space-y-12 pb-12">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <h1 className="text-4xl text-on-surface font-semibold tracking-tight">AI Recommendations</h1>
          <p className="text-on-surface-variant mt-2 text-sm max-w-2xl">
            Proactive operational adjustments generated by The Digital Foreman to optimize throughput.
          </p>
        </div>
      </div>

      <div className="space-y-6">
        {[
          {
            title: "Relocate High-Velocity Supplements",
            desc: "Items in category 'Supplements' are currently stored in Sector D. Relocating to Sector A (closer to packing stations) will reduce average picking time by 18 seconds per order.",
            impact: "High Impact",
            status: "Ready to Execute"
          },
          {
            title: "Delay Reorder for SKU-902",
            desc: "Current stock level is low, but predictive models indicate a 40% drop in seasonal demand starting next week. Waiting 14 days to reorder will prevent dead stock.",
            impact: "Medium Impact",
            status: "Review Required"
          },
          {
            title: "Schedule Maintenance for Conveyor C2",
            desc: "Acoustic sensor analysis detects potential motor fatigue on line C2. Preventive maintenance is recommended during the 2AM-4AM downtime window this Sunday.",
            impact: "Critical",
            status: "Pending Approval"
          }
        ].map((rec, i) => (
          <div key={i} className="bg-surface-container-lowest rounded-2xl p-6 shadow-[0_20px_40px_-10px_rgba(15,23,42,0.04)] border border-outline-variant/10 flex flex-col lg:flex-row lg:items-center justify-between gap-6 hover:border-primary/30 transition-colors">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                <BrainCircuit className="w-5 h-5 text-tertiary" />
                <h3 className="text-lg font-semibold text-on-surface">{rec.title}</h3>
                <span className={`text-xs ml-2 px-2 py-0.5 rounded-full ${rec.impact === 'Critical' ? 'bg-error/10 text-error' : 'bg-primary/10 text-primary'}`}>
                  {rec.impact}
                </span>
              </div>
              <p className="text-on-surface-variant text-sm leading-relaxed max-w-3xl">
                {rec.desc}
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row items-center gap-4 shrink-0">
              <span className="text-sm font-medium text-on-surface-variant">{rec.status}</span>
              <button className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-surface-container-high text-on-surface text-sm font-medium hover:bg-primary hover:text-white transition-colors">
                Take Action
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
